"""
Django settings for app_newspaper project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

'''
SENA CBA CENTRO DE BIOTECNOLOGIA AGROPECUARIA
PROGRAMACION DE SOFTWARE

FICHA: 2877795
AUTOR: NICOLAS ANDRES ACOSTA HIGUERA
PROYECTO: NEWSPAPER (app_newspaper/settings.py)
FECHA: 29/09/2024
VERSION: 1.0
'''


from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(=jx*7wl3j-*sy-)uj2p+$vhi_&(v1(%zsq1+1^qvf2a0k--q7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap5', # Agregamos la aplicación bootstrap5 a la lista de aplicaciones instaladas
    'crispy_forms', # Agregamos la aplicación crispy_forms a la lista de aplicaciones instaladas
    'crispy_bootstrap5', # Agregamos la aplicación crispy_bootstrap5 a la lista de aplicaciones instaladas
    'accounts.apps.AccountsConfig', # Agregamos la aplicación accounts a la lista de aplicaciones instaladas
    'pages.apps.PagesConfig', # Agregamos la aplicación pages a la lista de aplicaciones instaladas
    'articles.apps.ArticlesConfig', # Agregamos la aplicación articles a la lista de aplicaciones instaladas
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app_newspaper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'], # Definimos la carpeta templates como directorio de plantillas.
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app_newspaper.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES = [BASE_DIR / 'static'] # Definimos la carpeta static como directorio de archivos estáticos.

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.CustomUser' # Definimos la clase CustomUser como modelo de usuario
LOGIN_REDIRECT_URL = 'home' # Definimos la URL de redirección al iniciar sesión
LOGOUT_REDIRECT_URL = 'home' # Definimos la URL de redirección al cerrar sesión

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5' # Definimos el paquete de plantillas permitido para Crispy Forms
CRISPY_TEMPLATE_PACK = 'bootstrap5' # Definimos el paquete de plantillas para Crispy Forms

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # Definimos la consola como backend de correo electrónico


USE_I18N = True # Habilitamos la internacionalización

LANGUAGE_CODE = 'es-co' # Definimos el código de idioma

USE_TZ = True # Habilitamos la zona horaria

TIME_ZONE = 'America/Bogota' # Definimos la zona horaria
